# Assignment 1 - NumPy
---

## Exercise 1: Array Creation

**You can only use NumPy's built-in array creation methods to answer the below questions.**

### 1.1

Import NumPY.

In [1]:
# 1.1 Answer
import numpy as np

### 1.2

Create a 1D array of ODD numbers between 1 and 15 (inclusive).

In [2]:
# 1.2 Answer
odd_numbers = np.arange(1, 16, 2)
print(odd_numbers)

[ 1  3  5  7  9 11 13 15]


### 1.2

Create a 1D array of EVEN numbers between 0 and -20 (inclusive).

In [3]:
# 1.2 Answer
even_numbers = np.arange(0, -21, -2)
print(even_numbers)

[  0  -2  -4  -6  -8 -10 -12 -14 -16 -18 -20]


### 1.3

Create an array of 7 ones. Make sure all the elements are integers, not floats.

In [4]:
# 1.3 Answer
seven_ones = np.ones(7, dtype=int)
seven_ones

array([1, 1, 1, 1, 1, 1, 1])

### 1.4

Create an array of 7 eights. Make sure all the elements are integers, not floats.

In [5]:
# 1.4 Answer
seven_eights = 8 * np.ones(7, dtype=int)
seven_eights

array([8, 8, 8, 8, 8, 8, 8])

### 1.5

Create a 2D array of integers from -5 to -50. 

In [6]:
# 1.5 Answer
# Start by creating an array of integers
array_1d = np.arange(-5, -51, -1)

In [9]:
# Reshape the 1D array into a 2D array
array_2d = array_1d.reshape(6, 9)

array_2d

ValueError: cannot reshape array of size 46 into shape (6,9)

### 1.6

Create an array of 5 random numbers between 0 and 1.

In [8]:
# 1.6
np.random.random(5)

array([0.05856811, 0.34632759, 0.8148523 , 0.15527462, 0.87061513])

### 1.7

Create an array of 30 random numbers from a standard normal distribution.

In [12]:
# 1.7
np.random.randn(30)

array([ 0.37453492,  0.10338728,  0.81612688, -0.67375682,  0.2208861 ,
        1.3012772 , -0.14320511,  0.31916627, -0.02395561, -0.20814769,
        0.18967467, -0.08266843, -0.1186324 ,  1.62508878, -0.97431419,
        1.08105881,  0.94090491, -2.4687278 ,  0.93904826,  0.24897068,
       -0.15591865, -0.67156588, -0.2030819 , -0.65754392,  1.37810051,
       -1.27234415,  0.14202321, -0.67263364,  1.20736203,  0.28498673])

### 1.8

Recreate the following array:

    array([[[ 1,  2,  3],
            [ 4,  5,  6],
            [ 7,  8,  9]],

           [[10, 11, 12],
            [13, 14, 15],
            [16, 17, 18]]])


In [13]:
# 1.8 Answer
nested_list = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12],[13, 14, 15], [16, 17, 18]]]
nested_list       

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]

In [14]:
# 2D array with 3 rows and 3 columns

np.array(nested_list)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### 1.9 

Create an array of 8 evenly spaced numbers between 0 and 1 (inclusive).

In [15]:
# 1.9 Answer
# Returns a specified number of evenly spaced values in a given range. 
np.linspace(0,1,8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

## Exercise 2: Indexing and Selection

**Make sure your run the below cell. This is the array you will be working with.**

In [16]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### 2.1

Select the numbers 29 and 30 from the array.

Your output should look like this:
    
    array([29, 30])

In [17]:
# 2.1 Answer
arr[-1,-2:]

array([29, 30])

### 2.2

Select the number 13 from the array.

In [18]:
# 2.2 Answer
arr[2,2]

13

### 2.3

Select the numbers 14, 19, and 24 from the array.

Your output should look like this:

    array([[14],
           [19],
           [24]])

In [19]:
# 2.3 Answer
arr[2:5,3:4]

array([[14],
       [19],
       [24]])

### 2.4

Write a code that produces the following output:

    array([[21, 22, 23, 24, 25],
           [26, 27, 28, 29, 30]])

In [20]:
# 2.4 Answer
arr[4:6, 0:6]

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### 2.5

Write a code that produces the following output:

    array([[ 3,  4],
           [ 8,  9],
           [13, 14],
           [18, 19],
           [23, 24],
           [28, 29]])

In [21]:
# 2.5 Answer
arr[0:6,2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24],
       [28, 29]])

## Exercise 3: More NumPy!

**Make sure your run the below cell. This is the array you will be working with.**

**You can only use NumPy's built-in array creation methods to answer the below questions.**

In [22]:
arr = np.arange(5,101,5).reshape(5,4)
arr

array([[  5,  10,  15,  20],
       [ 25,  30,  35,  40],
       [ 45,  50,  55,  60],
       [ 65,  70,  75,  80],
       [ 85,  90,  95, 100]])

### 3.1

What is the sum of the values in arr?

In [23]:
# 3.1 Answer
arr.sum()

1050

### 3.2

What is the sum of values of each row in arr?

In [24]:
# 3.2 Answer
# Use axis=0 (columns) and axis=1 (rows)
arr.sum(axis=1)

array([ 50, 130, 210, 290, 370])

### 3.3

What is the min value in each column?

In [25]:
# 3.3 Answer
arr.min(axis=0)

array([ 5, 10, 15, 20])

### 3.4

Convert the rows in arr into columns, and the columns into rows.

Hint: Your new array should have a different shape.

In [26]:
# 3.4 Answer
transposed_arr = arr.transpose()
print(transposed_arr)

[[  5  25  45  65  85]
 [ 10  30  50  70  90]
 [ 15  35  55  75  95]
 [ 20  40  60  80 100]]


### 3.5

What is the square root of all the elements in arr?

In [27]:
# 3.5 Answer
arr_sqrt = arr ** 0.5
print(arr_sqrt)

[[ 2.23606798  3.16227766  3.87298335  4.47213595]
 [ 5.          5.47722558  5.91607978  6.32455532]
 [ 6.70820393  7.07106781  7.41619849  7.74596669]
 [ 8.06225775  8.36660027  8.66025404  8.94427191]
 [ 9.21954446  9.48683298  9.74679434 10.        ]]


## Bonus Question

Create a 4x4 identity matrix that matches this array:

    array([[0, 0, 0, 0],
           [1, 0, 0, 0],
           [0, 1, 0, 0],
           [0, 0, 1, 0]])
       
Pay attention to the location of the diagonal ones, as well as the data type of the above array.

[Click here for a hint.](https://numpy.org/doc/stable/reference/generated/numpy.eye.html)

In [28]:
# Bonus question answer
#Trial and error and here we go
np.eye(4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# The End!